Controllers/ProductController.cs
using System.IO;
using ecommerce.Models;
using ecommerce.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using Microsoft.AspNetCore.Mvc.Rendering;
using ecommerce.Data.Repositories;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;

namespace ecommerce.Controllers

{
    [Authorize(Roles = "Admin")]
    public class ProductController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly IWebHostEnvironment hostingEnvironment;

        public ProductController(IProductRepository productRepository, ICategoryRepository categoryRepository, IWebHostEnvironment hostingEnvironment)
        {
            _productRepository = productRepository;
            _categoryRepository = categoryRepository;
            this.hostingEnvironment = hostingEnvironment;
        }
        // GET: ProductController
        [AllowAnonymous]
        public ActionResult Index()
        {
            var model = _productRepository.GetAll();


            return View(model);
        }
        [AllowAnonymous]
        public ViewResult List(string category)
        {
            string _category = category;
            IEnumerable<Product> products;
            string currentCategory = string.Empty;

            if (string.IsNullOrEmpty(category))
            {
                products = _productRepository.GetAll().OrderBy(p => p.id);
                currentCategory = "All products";
            }
            else
            {
             
                        if (_categoryRepository.GetAll().Where(p=>p.name.Equals(_category))!=null)
                        {
                            
                            products = _productRepository.GetAll().Where(p => p.category.name.Equals(_category)).OrderBy(p => p.name);
                        }
                else
                {
                     products = _productRepository.GetAll().OrderBy(p => p.id);
                }
                   
                           
                    
               

                currentCategory = _category;
            }

            return View(new ProductsListViewModel
            {
                products = products,
                CurrentCategory = currentCategory
            });
        } 
        // GET: ProductController/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id)
        {
            
            var model = _productRepository.GetProduct(id);
            model.category = _categoryRepository.GetById(_productRepository.GetProductCategory(id));
        
            return View(model);
        }

        // GET: ProductController/Create
        public ActionResult Create()
        {
            ViewBag.categoryId = new SelectList(_categoryRepository.GetAll(), "id", "name");
            return View();
        }

        // POST: ProductController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = null;

                // If the Photo property on the incoming model object is not null, then the user
                // has selected an image to upload.
                if (model.Photo != null)
                {
                    // The image must be uploaded to the images folder in wwwroot
                    // To get the path of the wwwroot folder we are using the inject
                    // HostingEnvironment service provided by ASP.NET Core

                    string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath, "images");

                    // To make sure the file name is unique we are appending a new
                    // GUID value and an underscore to the file name

                    uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Photo.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                    // Use CopyTo() method provided by IFormFile interface to
                    // copy the file to wwwroot/images folder

                    model.Photo.CopyTo(new FileStream(filePath, FileMode.Create));
                }

                Product newProduct = new Product
                {
                    name = model.name,
                    description = model.description,
                    price = model.price,
                    quantity = model.quantity,
                    categoryId = model.categoryId,
                    isNewCollection=model.isNewCollection,
                   
                    //ViewBag.category = new SelectList(_categoryRepository.GetAll(), "SchoolID", "SchoolName");
                    // Store the file name in PhotoPath property of the employee object
                    // which gets saved to the Employees database table
                    imageUrl = uniqueFileName
                };
                ViewBag.categoryId = new SelectList(_categoryRepository.GetAll(), "id", "name",model.categoryId);

                _productRepository.Add(newProduct);
                return RedirectToAction("details", new { newProduct.id });
            }

            return View();
        }

        // GET: ProductController/Edit/5
        public ActionResult Edit(int id)
        {
            Product oldproduct = _productRepository.GetProduct(id);
            ViewBag.categoryId = new SelectList(_categoryRepository.GetAll(), "id", "name");
            ProductEditViewModel productEditViewModel = new ProductEditViewModel
            {
            id= oldproduct.id,
            name = oldproduct.name,
            price = oldproduct.price,
            ExistingimageUrl = oldproduct.imageUrl,
            quantity = oldproduct.quantity,
            description = oldproduct.description,
            isNewCollection = oldproduct.isNewCollection,
            categoryId = oldproduct.categoryId,
            };
           
            return View(productEditViewModel);
        }

        // POST: ProductController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProductEditViewModel model) { 
         if (ModelState.IsValid)
            {   // Retrieve the product being edited from the database
                Product product = _productRepository.GetProduct(model.id);
                // Update the employee object with the data in the model object
                product.name = model.name;
                product.price = model.price;
                product.quantity = model.quantity;
                product.imageUrl = model.ExistingimageUrl;
                product.description = model.description;
                product.isNewCollection = model.isNewCollection;
                ViewBag.categoryId = new SelectList(_categoryRepository.GetAll(), "id", "name", model.categoryId);

                product.categoryId = model.categoryId;
                // If the user wants to change the photo, a new photo will be
                // uploaded and the Photo property on the model object receives
                // the uploaded photo. If the Photo property is null, user did
                // not upload a new photo and keeps his existing photo
                if (model.Photo != null){
                    // If a new photo is uploaded, the existing photo must be
                    // deleted. So check if there is an existing photo and delete
                    if (model.ExistingimageUrl != null)
                        {string filePath = Path.Combine(hostingEnvironment.WebRootPath,
                                "images", model.ExistingimageUrl);
                         System.IO.File.Delete(filePath);
                        }
                    // Save the new photo in wwwroot/images folder and update
                    // PhotoPath property of the employee object which will be
                    // eventually saved in the database
                    product.imageUrl= ProcessUploadedFile(model);}

                // Call update method on the repository service passing it the
                // employee object to update the data in the database table
               
                Product updatedProduct = _productRepository.Edit(product);
                    if (updatedProduct != null)
                        return RedirectToAction("index");
                    else
                        return NotFound();
                }
                    return View(model);
                }

    [NonAction]
    private string ProcessUploadedFile(ProductEditViewModel model)
    {
        string uniqueFileName = null;

        if (model.Photo != null)
        {
            string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath, "images");
            uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Photo.FileName;
            string filePath = Path.Combine(uploadsFolder, uniqueFileName);
            using (var fileStream = new FileStream(filePath, FileMode.Create))
            {
                model.Photo.CopyTo(fileStream);
            }
        }

        return uniqueFileName;
    }

    // GET: ProductController/Delete/5
    public ActionResult Delete(int id)
        {
            Product p = _productRepository.GetProduct(id);
            if (p == null)
                return NotFound();
            else
                return View(p);
            
        }

        // POST: ProductController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Product p)
        {
            try
            {
                Product p1 =_productRepository.Delete(p);
                if (p1 != null)
                    return RedirectToAction(nameof(Index));
                else
                    return View();

Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ecommerce.Areas.Admin.Models;
using ecommerce.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ecommerce.Areas.Admin.Controllers
{
   
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<IdentityUser> _userManager;
        ApplicationDbContext _db;
        public RoleController(RoleManager<IdentityRole> roleManager, ApplicationDbContext db, UserManager<IdentityUser> userManager)
        {
            _roleManager = roleManager;
            _db = db;

            _userManager = userManager;
        }

        // GET: RoleController
        public ActionResult Index()
        {
            var roles = _roleManager.Roles.ToList();
            ViewBag.Roles = roles;

            return View();
        }

        // GET: RoleController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: RoleController/Create
        public async Task<IActionResult> Create()
        {
            return View();
        }

        // POST: RoleController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string name)
        {
            IdentityRole role = new IdentityRole();
            role.Name = name;
            var isExist = await _roleManager.RoleExistsAsync(role.Name);
            if (isExist)
            {
                ViewBag.mgs = "This role is aldeady exist";
                ViewBag.name = name;
                return View();
            }
            var result = await _roleManager.CreateAsync(role);
            if (result.Succeeded)
            {
                TempData["save"] = "Role has been saved successfully";
                return RedirectToAction(nameof(Index));
            }
            return View();

        }

        // GET: RoleController/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            ViewBag.id = role.Id;
            ViewBag.name = role.Name;
            return View();

        }

        // POST: RoleController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, string name)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            role.Name = name;
            var isExist = await _roleManager.RoleExistsAsync(role.Name);
            if (isExist)
            {
                ViewBag.mgs = "This role is aldeady exist";
                ViewBag.name = name;
                return View();
            }
            var result = await _roleManager.UpdateAsync(role);
            if (result.Succeeded)
            {
                TempData["save"] = "Role has been updated successfully";
                return RedirectToAction(nameof(Index));
            }
            return View();

        }

        // GET: RoleController/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            ViewBag.id = role.Id;
            ViewBag.name = role.Name;
            return View();

        }

        // POST: RoleController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }

            var result = await _roleManager.DeleteAsync(role);
            if (result.Succeeded)
            {
                 TempData["delete"] = "Role has been deleted successfully";
                return RedirectToAction(nameof(Index));
            }
            return View();

        }

        public async Task<IActionResult> Assign()
        {
            //ViewData["UserId"] = new SelectList(_userManager.GetUserNameAsync, "id", "name");
            //ViewData["UserId"] = new SelectList(_db.ApplicationUsers.Where(f => f.LockoutEnd < DateTime.Now || f.LockoutEnd == null).ToList(), "Id", "UserName");
            ViewData["UserId"] = new SelectList(_userManager.Users.ToList(),"Id","UserName");

            ViewData["RoleId"] = new SelectList(_roleManager.Roles.ToList(), "Name", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Assign(RoleUserVm roleUser)
        {
            var user = _userManager.Users.FirstOrDefault(c => c.Id == roleUser.UserId);
            var isCheckRoleAssign = await _userManager.IsInRoleAsync(user, roleUser.RoleId);
            if (isCheckRoleAssign)
            {
                ViewBag.mgs = "This user already assign this role.";
                ViewData["UserId"] = new SelectList(_userManager.Users.Where(f => f.LockoutEnd < DateTime.Now || f.LockoutEnd == null).ToList(), "Id", "UserName");
                ViewData["RoleId"] = new SelectList(_roleManager.Roles.ToList(), "Name", "Name");
                return View();
            }
            var role = await _userManager.AddToRoleAsync(user, roleUser.RoleId);
            if (role.Succeeded)
            {
                TempData["save"] = "User Role assigned.";
                return RedirectToAction(nameof(AssignUserRole));
            }
            return View();
        }

        public ActionResult AssignUserRole()
        {
            var result = from ur in _db.UserRoles
                         join r in _db.Roles on ur.RoleId equals r.Id
                         join a in _userManager.Users on ur.UserId equals a.Id
                         select new UserRoleMapping()
                         {
                             UserId = ur.UserId,
                             RoleId = ur.RoleId,
                             UserName = a.UserName,
                             RoleName = r.Name
                         };
            ViewBag.UserRoles = result;
            return View();
        }
      




    }
}

Views/Shared/Carousel.cshtml
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="~/images/subbanner1.jpg" alt="First slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="~/images/femme-slide.jpg" alt="Second slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="~/images/Main-Banner1.jpg" alt="Third slide">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

Views/Shared/ProductOverviewSummary.cshtml
@model Product
@{var photoPath = "~/images/" + (Model.imageUrl ?? "noimage.jpg"); }
    <div class="col-sm-4 col-lg-4 col-md-4">
        <div class="thumbnail">
            <img src="@photoPath" asp-append-version="true" height="100" width="100" />
            <div class="caption">
                <h3 class="pull-right">@Model.price</h3>
                <h3>
                    <a asp-controller="Drink" asp-action="Details" asp-route-id="@Model.id">@Model.name</a>
                </h3>
                <p>@Model.description</p>
            </div>
            <div class="addToCart text-right">
                <p class="button ">
                    <a class="btn btn-success " id="cartButton" asp-controller="ShoppingCart" asp-action="AddToShoppingCart" asp-route-id="@Model.id">
                        Ajouter au panier
                    </a>
                </p>
            </div>
        </div>
    </div>

Views/Shared/ProductsSummary.cshtml
@model Product
@{var photoPath = "~/images/" + (Model.imageUrl ?? "noimage.jpg"); }
<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="card">
        <div style="text-align: center">
            <img src="@photoPath" asp-append-version="true" height="300px" width="200px" />
        </div>
        <div class="caption">
            <center>
                <h4>
                    <a asp-controller="Product" asp-action="Details" asp-route-id="@Model.id">@Model.name</a>
                </h4>
                <h5 class="pull-right">@Model.price DT</h5>
                <p>@Model.description</p>
            </center>
        </div>
        <div class="addToCart text-right">
            <p class="button" style="text-align: center">
                <a  asp-controller="ShoppingCart" asp-action="AddToShoppingCart" asp-route-id="@Model.id" class="btn btn-success" id="cartButton">
                    <i class="fas fa-shopping-cart"></i> Ajouter au panier 
                </a>
            </p>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Fashion Store</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.11.2/build/css/alertify.min.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm fixed-top navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-color: #e3690b;">
            <div class="container">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-tshirt"></i> FashionStore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-home"></i> Accueil</a>
                        </li>
                        <li class="nav-item">
                            <form class="navbar-nav" asp-controller="Product" asp-action="Search" method="get">
                                <input type="text" class="form-control" placeholder="Recherche d'un produit" name="searchString" value="@ViewData["searchString"]">
                            </form>
                        </li>
                        @if (!User.IsInRole("Admin"))
                        { @await Component.InvokeAsync("CategoryMenu")

                          <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="ShoppingCart" asp-action="Index"><i class="fas fa-shopping-cart"></i></a>
                           </li>
                        }
                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        { <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Menu
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <li><a class="dropdown-item" asp-controller="Category" asp-action="Index">Gérer les catégories</a></li>                       
                                    <li><a class="dropdown-item" asp-controller="Product" asp-action="Index">Gérer les produits</a></li>
                                    <li class="dropright-submenu">
                                        <a class="dropdown-item dropdown-toggle" href="#">Gérer les utilisateurs</a>
                                        <ul class="dropdown-menu">
                                            <li><a class="dropdown-item" asp-area="" asp-controller="Role" asp-action="Index">Role</a></li>
                                            <li><a class="dropdown-item" asp-area="" asp-controller="Role" asp-action="AssignUserRole">Utilisateurs</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                        }

                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - FashionStore - <a asp-area="" asp-controller="Home" asp-action="Index">Accueil</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

    <script>
        $('.dropdown-menu a.dropdown-toggle').on('click', function (e) {
            if (!$(this).next().hasClass('show')) {
                $(this).parents('.dropdown-menu').first().find('.show').removeClass('show');
            }
            var $subMenu = $(this).next('.dropdown-menu');
            $subMenu.toggleClass('show');


            $(this).parents('li.nav-item.dropdown.show').on('hidden.bs.dropdown', function (e) {
                $('.dropdown-submenu .show').removeClass('show');
            });


            return false;
        });
    </script>