Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ecommerce.Models
{
    public class Product
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int id { get; set; }
        public string name { get; set; }

        public float price { get; set; }
        public int quantity { get; set; }
        public bool isNewCollection { get; set; }
        public string description { get; set; }
        [ForeignKey("categoryId")]
        public int categoryId { get; set; }
        public string imageUrl { get; set; }
        public virtual Category category { get; set; }
       
    }
}

ViewModels/CreateViewModel.cs
using Microsoft.AspNetCore.Http;

namespace ecommerce.ViewModels
{
    public class CreateViewModel
    {   
        public string name { get; set; }

        public string description { get; set; }

        public string category { get; set; }
        public float price { get; set; }
        
        public int quantity { get; set; }
        public bool isNewCollection { get; set; }
        public int categoryId { get; set; }

        public IFormFile Photo { get; set;}
    }
}

Controllers/ProductController.cs
using System.IO;
using ecommerce.Models;
using ecommerce.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using Microsoft.AspNetCore.Mvc.Rendering;
using ecommerce.Data.Repositories;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;

namespace ecommerce.Controllers

{
    [Authorize(Roles = "Admin")]
    public class ProductController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly IWebHostEnvironment hostingEnvironment;

        public ProductController(IProductRepository productRepository, ICategoryRepository categoryRepository, IWebHostEnvironment hostingEnvironment)
        {
            _productRepository = productRepository;
            _categoryRepository = categoryRepository;
            this.hostingEnvironment = hostingEnvironment;
        }
        // GET: ProductController
        [AllowAnonymous]
        public ActionResult Index()
        {
            var model = _productRepository.GetAll();


            return View(model);
        }
        [AllowAnonymous]
        public ViewResult List(string category)
        {
            string _category = category;
            IEnumerable<Product> products;
            string currentCategory = string.Empty;

            if (string.IsNullOrEmpty(category))
            {
                products = _productRepository.GetAll().OrderBy(p => p.id);
                currentCategory = "All products";
            }
            else
            {
             
                        if (_categoryRepository.GetAll().Where(p=>p.name.Equals(_category))!=null)
                        {
                            
                            products = _productRepository.GetAll().Where(p => p.category.name.Equals(_category)).OrderBy(p => p.name);
                        }
                else
                {
                     products = _productRepository.GetAll().OrderBy(p => p.id);
                }
                   
                           
                    
               

                currentCategory = _category;
            }

            return View(new ProductsListViewModel
            {
                products = products,
                CurrentCategory = currentCategory
            });
        } 
        // GET: ProductController/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id)
        {
            
            var model = _productRepository.GetProduct(id);
            model.category = _categoryRepository.GetById(_productRepository.GetProductCategory(id));
        
            return View(model);
        }

        // GET: ProductController/Create
        public ActionResult Create()
        {
            ViewBag.categoryId = new SelectList(_categoryRepository.GetAll(), "id", "name");
            return View();
        }

        // POST: ProductController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = null;

                // If the Photo property on the incoming model object is not null, then the user
                // has selected an image to upload.
                if (model.Photo != null)
                {
                    // The image must be uploaded to the images folder in wwwroot
                    // To get the path of the wwwroot folder we are using the inject
                    // HostingEnvironment service provided by ASP.NET Core

                    string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath, "images");

                    // To make sure the file name is unique we are appending a new
                    // GUID value and an underscore to the file name

                    uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Photo.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                    // Use CopyTo() method provided by IFormFile interface to
                    // copy the file to wwwroot/images folder

                    model.Photo.CopyTo(new FileStream(filePath, FileMode.Create));
                }

                Product newProduct = new Product
                {
                    name = model.name,
                    description = model.description,
                    price = model.price,
                    quantity = model.quantity,
                    categoryId = model.categoryId,
                    isNewCollection=model.isNewCollection,
                   
                    //ViewBag.category = new SelectList(_categoryRepository.GetAll(), "SchoolID", "SchoolName");
                    // Store the file name in PhotoPath property of the employee object
                    // which gets saved to the Employees database table
                    imageUrl = uniqueFileName
                };
                ViewBag.categoryId = new SelectList(_categoryRepository.GetAll(), "id", "name",model.categoryId);

                _productRepository.Add(newProduct);
                return RedirectToAction("details", new { newProduct.id });
            }

            return View();
        }

        // GET: ProductController/Edit/5
        public ActionResult Edit(int id)
        {
            Product oldproduct = _productRepository.GetProduct(id);
            ViewBag.categoryId = new SelectList(_categoryRepository.GetAll(), "id", "name");
            ProductEditViewModel productEditViewModel = new ProductEditViewModel
            {
            id= oldproduct.id,
            name = oldproduct.name,
            price = oldproduct.price,
            ExistingimageUrl = oldproduct.imageUrl,
            quantity = oldproduct.quantity,
            description = oldproduct.description,
            isNewCollection = oldproduct.isNewCollection,
            categoryId = oldproduct.categoryId,
            };
           
            return View(productEditViewModel);
        }

        // POST: ProductController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProductEditViewModel model) { 
         if (ModelState.IsValid)
            {   // Retrieve the product being edited from the database
                Product product = _productRepository.GetProduct(model.id);
                // Update the employee object with the data in the model object
                product.name = model.name;
                product.price = model.price;
                product.quantity = model.quantity;
                product.imageUrl = model.ExistingimageUrl;
                product.description = model.description;
                product.isNewCollection = model.isNewCollection;
                ViewBag.categoryId = new SelectList(_categoryRepository.GetAll(), "id", "name", model.categoryId);

                product.categoryId = model.categoryId;
                // If the user wants to change the photo, a new photo will be
                // uploaded and the Photo property on the model object receives
                // the uploaded photo. If the Photo property is null, user did
                // not upload a new photo and keeps his existing photo
                if (model.Photo != null){
                    // If a new photo is uploaded, the existing photo must be
                    // deleted. So check if there is an existing photo and delete
                    if (model.ExistingimageUrl != null)
                        {string filePath = Path.Combine(hostingEnvironment.WebRootPath,
                                "images", model.ExistingimageUrl);
                         System.IO.File.Delete(filePath);
                        }
                    // Save the new photo in wwwroot/images folder and update
                    // PhotoPath property of the employee object which will be
                    // eventually saved in the database
                    product.imageUrl= ProcessUploadedFile(model);}

                // Call update method on the repository service passing it the
                // employee object to update the data in the database table
               
                Product updatedProduct = _productRepository.Edit(product);
                    if (updatedProduct != null)
                        return RedirectToAction("index");
                    else
                        return NotFound();
                }
                    return View(model);
                }

    [NonAction]
    private string ProcessUploadedFile(ProductEditViewModel model)
    {
        string uniqueFileName = null;

        if (model.Photo != null)
        {
            string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath, "images");
            uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Photo.FileName;
            string filePath = Path.Combine(uploadsFolder, uniqueFileName);
            using (var fileStream = new FileStream(filePath, FileMode.Create))
            {
                model.Photo.CopyTo(fileStream);
            }
        }

        return uniqueFileName;
    }

    // GET: ProductController/Delete/5
    public ActionResult Delete(int id)
        {
            Product p = _productRepository.GetProduct(id);
            if (p == null)
                return NotFound();
            else
                return View(p);
            
        }

        // POST: ProductController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Product p)
        {
            try
            {
                Product p1 =_productRepository.Delete(p);
                if (p1 != null)
                    return RedirectToAction(nameof(Index));
                else
                    return View();

Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ecommerce.Data.Repositories;
using ecommerce.Models;
using ecommerce.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ecommerce.Controllers
{
    [Authorize(Roles = "User")]
    public class ShoppingCartController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ShoppingCart _shoppingCart;

        public ShoppingCartController(IProductRepository productRepository, ShoppingCart shoppingCart)
        {
            _productRepository = productRepository;
            _shoppingCart = shoppingCart;
        }
        // GET: ShoppingCartController
        [Authorize]
        public ViewResult Index()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };
            return View(shoppingCartViewModel);
        }
        [HttpGet]
        [Authorize]
       
        public RedirectToActionResult AddToShoppingCart(int id)
        {
            Console.WriteLine(id);
            Product selectedProduct = _productRepository.products.FirstOrDefault(p => p.id == id);
           
            if (selectedProduct != null)
            {
                
                _shoppingCart.AddToCart(selectedProduct, 1);
            }
           
            return RedirectToAction("Index");
        }
        [Authorize]
        public RedirectToActionResult RemoveFromShoppingCart(int id)
        {
            var selectedProduct = _productRepository.products.FirstOrDefault(p => p.id == id);
            if (selectedProduct != null)
            {
                _shoppingCart.RemoveFromCart(selectedProduct);
            }
            return RedirectToAction("Index");
        }
    }
}

Views/Product/Create.cshtml
@model ecommerce.ViewModels.CreateViewModel

@{
    ViewData["Title"] = "Create";
}



<br/><br /><br />
<h4>Ajouter un arcicle</h4>


<hr />
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-action="Create">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="price" class="control-label"></label>
                <input asp-for="price" class="form-control" />
                <span asp-validation-for="price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="quantity" class="control-label"></label>
                <input asp-for="quantity" class="form-control" />
                <span asp-validation-for="quantity" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="isNewCollection" /> @Html.DisplayNameFor(model => model.isNewCollection)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="description" class="control-label"></label>
                <input asp-for="description" class="form-control" />
                <span asp-validation-for="description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="categoryId" class="control-label"></label>
                <select asp-for="categoryId" asp-items="ViewBag.categoryId" class="custom-select mr-sm-2">
                    <option value="">Selectionner une valeur</option>
                </select>
                <span asp-validation-for="categoryId" class="text-danger"></span>
            </div>
            <div class="form-group row">
                <label asp-for="Photo" class="col-sm-2 col-form-label"></label>
                <div class="col-sm-10">
                    <div class="custom-file">
                        <input asp-for="Photo" class="form-control custom-file-input">
                        <label class="custom-file-label">Choose File...</label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@*@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}*@
@section Scripts {
    <script>
        $(document).ready(function () {
            $('.custom-file-input').on("change", function () {
                var fileName = $(this).val().split("\\").pop();
                $(this).next('.custom-file-label').html(fileName);
            });
        });
    </script>
}

Views/Product/Delete.cshtml
@model ecommerce.Models.Product

@{
    ViewData["Title"] = "Delete";
    var photoPath = "~/images/" + (Model.imageUrl ?? "noimage.jpg");
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.quantity)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.quantity)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.category)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.category)
        </dd>
        <dt class="col-sm-2">
            <label><b>Photo</b> </label>
        </dt>
        <dd class="col-sm-10">
            <div class="card-body text-left">
                <img src="@photoPath" asp-append-version="true" height="100" width="100" />
            </div>
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="index" asp-controller="Product" class="btn btn-primary">Cancel</a>
    </form>
</div>

Views/Product/Details.cshtml
@model ecommerce.Models.Product
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@{
    ViewData["Title"] = "Details";
    var photoPath = "~/images/" + (Model.imageUrl ?? "noimage.jpg");
}
<br />
<br/>
<br/>
<h4>Détails</h4>
<hr />
@if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
{
    <div>
    
        <dl class="row">
            <dt class="col-sm-2">
                <label><b>Photo</b> </label>
            </dt>
            <dd class="col-sm-10">
                <div class="card-body text-left">
                    <img src="@photoPath" asp-append-version="true" height="100" width="100" />
                </div>
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.price)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.price)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.quantity)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.quantity)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.description)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.description)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.category.name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.category.name)
            </dd>

        </dl>
    </div>
    <div>
        <a asp-action="Edit" asp-route-id="@Model.id">Edit</a> |
        <a asp-action="Index">Back to List</a>
    </div>
}
<!--Interface Pour le client-->
@if ((SignInManager.IsSignedIn(User) && !User.IsInRole("Admin")) || !SignInManager.IsSignedIn(User))


{
    <div class="container marginTop">
        <div class="row">
            <div class="card">
                <div class="text-center view overlay hm-white-slight">
                    <img src="@photoPath" class="img-fluid" asp-append-version="true" height="100" width="100" />

                </div>
                <div class="card-block" style="text-align: center">
                    <!--Title-->
                    <h5 class="card-title"> @Html.DisplayFor(model => model.name)</h5>
                    <h5 class="card-title"> @Html.DisplayFor(model => model.price)</h5>
                    <!--Text-->
                    <p class="card-text">@Html.DisplayFor(model => model.description)</p>
                    <p class="btn btn-group pull-right">
                        <a class="btn btn-secondary" id="cartButton" asp-controller="Product" asp-action="Index"><i class="fa fa-arrow-alt-circle-left"> Ajouter plus de produits</i></a>
                        <a asp-controller="ShoppingCart" asp-action="AddToShoppingCart" asp-route-id="@Model.id" class="btn btn-success" id="cartButton">
                            <i class="fas fa-shopping-cart"></i> Ajouter au panier
                        </a>
                    </p>
                </div>
            </div>
        </div>
    </div>
}

Views/Product/Edit.cshtml
@model ecommerce.ViewModels.ProductEditViewModel

@{
    ViewData["Title"] = "Edit";
    var photoPath = "~/images/" + (Model.ExistingimageUrl ?? "noimage.jpg");
}

<br/>
<br />
<br />
<h4>Modifier le produit</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Product" enctype="multipart/form-data" method="post" class="mt-3">
            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <input hidden asp-for="ExistingimageUrl" />
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="price" class="control-label"></label>
                <input asp-for="price" class="form-control" />
                <span asp-validation-for="price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="quantity" class="control-label"></label>
                <input asp-for="quantity" class="form-control" />
                <span asp-validation-for="quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="description" class="control-label"></label>
                <input asp-for="description" class="form-control" />
                <span asp-validation-for="description" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="isNewCollection" /> @Html.DisplayNameFor(model => model.isNewCollection)
                </label>
            </div>
            <div class="form-group row">
                <label asp-for="categoryId" class="col-sm-2 col-form-label"></label>
                <div class="col-sm-10">
                    <select asp-for="categoryId" class="custom-select mr-sm-2"
                            asp-items="ViewBag.categoryId">
                    </select>
                    <span asp-validation-for="categoryId" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label asp-for="Photo" class="col-sm-2 col-form-label"></label>
                <div class="col-sm-10">
                    <div class="custom-file">
                        <input asp-for="Photo" class="custom-file-input form-control">
                        <label class="custom-file-label">cliquer ici pour changer la photo</label>
                    </div>
                </div>
            </div>
            <div class="form-group row col-sm-4 offset-4">
                <img src="@photoPath" asp-append-version="true" height="100" width="100" />
            </div>
            <div class="form-group row">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-primary">Update</button>
                    <a asp-action="index" asp-controller="Product" class="btn btn-primary">Cancel</a>
                </div>
            </div>


            <div>
                <a asp-action="Index">Back to List</a>
            </div>


            @section Scripts {
                <script>
                    $(document).ready(function () {
                        $('.custom-file-input').on("change", function () {
                            var fileName = $(this).val().split("\\").pop();
                            $(this).next('.custom-file-label').html(fileName);
                        });
                    });
                </script>
            }
        </form>
    </div>
</div>

Views/Product/Index.cshtml
@model IEnumerable<ecommerce.Models.Product>
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@{
    ViewData["Title"] = "Index";
}
<br />
<br />
<br />
<br />
<h4>Liste des produits</h4>

@if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
{
    <p>
        <a class="btn btn-primary m-1" asp-action="Create">Ajouter un produit</a>
    </p>
}
<hr/>
<div class="card-deck">
    @foreach (var product in Model)
    {
        var photoPath = "~/images/" + (product.imageUrl ?? "noimage.jpg");


        <div class="card m-3" style="min-width: 18rem; max-width:30.5%;">
            <img class="card-img-top imageThumbnail" height="400px" width="300px" src="@photoPath"
                 asp-append-version="true" />
            <div class="card-header" style="text-align: center">
                <h5>@product.name</h5>
                <h5>@product.price DT</h5>
                @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                {
                    <h5><b>quantité disponible: </b>@product.quantity</h5>
                }

            </div>



            <div class="card-footer text-center">
                <a asp-controller="Product" asp-action="Details" asp-route-id="@product.id"
                   class="btn btn-primary m-1"><i class="fas fa-eye"></i> Voir détails</a>
                @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                {
                    <a asp-action="Edit" asp-controller="Product" class="btn btn-primary m-1" asp-route-id="@product.id"><i class="fas fa-edit"></i>Modifier</a>
                    <a asp-action="Delete" asp-controller="Product" class="btn btn-danger m-1" asp-route-id="@product.id"><i class="fas fa-trash-alt"></i>Supprimer</a>

                }
                else
                {
                    <a asp-controller="ShoppingCart" asp-action="AddToShoppingCart" asp-route-id="@product.id" class="btn btn-success" id="cartButton">
                        <i class="fas fa-shopping-cart"> Ajouter au panier</i>
                    </a>
                }
            </div>
        </div>
    }
</div>

Views/Product/List.cshtml
@model ecommerce.ViewModels.ProductsListViewModel

<br/><br/><br/>
<div class="row marginTop">
    @foreach (Product product in Model.products)
    {
        @Html.Partial("ProductsSummary", product)
    }
</div>